

trigger:
- main   # or your branch

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  jobs:
  - deployment: DeployToDemo
    displayName: 'Deploy to Demo Environment'
    environment: 'Demo_Environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Hello, world!"
            displayName: 'Run a one-line script'
          - script: |
              echo "Add other tasks to build, test, and deploy your project."
              echo "See https://aka.ms/yaml"
            displayName: 'Run a multi-line script'
